### PR TITLE
fix link to plugins site

### PR DESCRIPTION
**Pull request by dbox**
🔧 🔌

### CODE REVIEW

**Review by jescalan — APPROVED** [review]

**Comment by jescalan** [comment]
thank you! 🙏

**Comment by dbox** [comment]
👊 last place to change is the github description

**Comment by dbox** [comment]
and on root `reshape` group

**Comment by jescalan** [comment]
What is the root reshape group? Changed the description

**Comment by dbox** [comment]
image

**Comment by jescalan** [comment]
Ah yes, ok will update here too!

**Pull request merged**
